name: SAST - Semgrep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Instalar Semgrep
      - name: Install Semgrep
        run: pip install --upgrade pip semgrep

      # 4️⃣ Rodar Semgrep e gerar JSON
      - name: Run Semgrep scan (JSON)
        run: semgrep --config=https://semgrep.dev/p/python/lang/security --json > semgrep-report.json

      # 5️⃣ Upload do JSON como artifact
      - name: Upload JSON report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json

      # 6️⃣ Gerar relatório em Markdown (mais legível)
      - name: Generate Markdown report
        run: semgrep --config=https://semgrep.dev/p/python/lang/security --markdown > semgrep-report.md

      # 7️⃣ Upload do Markdown como artifact
      - name: Upload Markdown report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report-md
          path: semgrep-report.md
