name: SAST - Semgrep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Semgrep
        run: pip install --upgrade pip semgrep

      - name: Run Semgrep scan
        run: semgrep --config=https://semgrep.dev/p/python/lang/security --json > semgrep-report.json

      - name: Upload JSON report
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report
          path: semgrep-report.json

      - name: Generate Markdown report
        run: |
          pip install semgrep --upgrade
          semgrep --config=https://semgrep.dev/p/python/lang/security --markdown > semgrep-report.md

      - name: Upload Markdown report
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report-md
          path: semgrep-report.md
