name: SCA

on: [push, pull_request]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@v4
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}
      - run: snyk test --all-projects
