name: Prevent secrets
on: [push, pull_request]
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: trufflehog scan
        uses: trufflesecurity/trufflehog-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
