name: CI/CD Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # -------------------------
  # SAST – Semgrep
  # -------------------------
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=auto . > semgrep_report.txt || true

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report
          path: semgrep_report.txt

  # -------------------------
  # SCA – Snyk
  # -------------------------
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk Test
        run: snyk test > snyk_report.txt || true

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report
          path: snyk_report.txt

  # -------------------------
  # DAST – OWASP ZAP
  # -------------------------
  dast:
    runs-on: ubuntu-latest
    services:
      web:
        image: python:3.11
        options: >-
          --health-cmd "curl -f http://localhost:5000 || exit 1"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5
        ports:
          - 5000:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Run application
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          nohup python app.py &

      - name: Run OWASP ZAP Scan
        run: |
          docker run -v ${{ github.workspace }}:/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t http://host.docker.internal:5000 -r zap_report.html || true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
