name: Security Pipeline

on: [push, pull_request]

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/security-audit

  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@v4
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}
      - run: snyk test --all-projects

  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Run OWASP ZAP baseline
        uses: zaproxy/action-baseline@v1
        with:
          target: 'https://mindguard-demo-production.up.railway.app/'
